### ISSUE TITLE
Sitemap is not being generated correctly

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.googlenews#20]
We have this package installed in one customer and the news sitemap is returning a wrong number of items:

![selecao_009](https://cloud.githubusercontent.com/assets/341393/11398958/5438a2a4-936b-11e5-8f74-5c3e0dc871d5.png)

**Comment by hvelarde** [comment]
this one is a blocker for #16

**Comment by rodfersou** [comment]
https://support.google.com/news/publisher/answer/74288?hl=pt-BR&ref_topic=4359874

**Comment by hvelarde** [comment]
the issue description is wrong; in fact, the implementation we used in that customer is different from the one inside this package; anyway, the one in here also needs to be fixed because is not working neither.
